Autenticar usuário
adelsonsljunior/api-biblioteca pull request #5
Opened 2023-05-03 13:49 UTC by adelsonsljunior

## Implementada a autenticação de usuários  ([Issue 1](https://github.com/adelsonsljunior/api-biblioteca/issues/1))

### Operações dos Controllers de Users e Auth

#### create 
![create](https://user-images.githubusercontent.com/94010073/235934948-39606435-2c1d-4da5-b91d-3c1b264442bc.png)

#### login
![login](https://user-images.githubusercontent.com/94010073/235935111-3ca684fd-6fe6-4283-b94a-5db578146001.png)

#### index 
![index](https://user-images.githubusercontent.com/94010073/235935055-01da4a06-3dc1-4615-895d-b6e73834d43d.png)

#### show
![show](https://user-images.githubusercontent.com/94010073/235935025-735e6429-0ec0-4cb7-8290-f769540acf29.png)

#### update 
![update](https://user-images.githubusercontent.com/94010073/235935044-18ecad82-9b63-435b-8f62-a6e808d6f3f3.png)

#### logout
![logout](https://user-images.githubusercontent.com/94010073/235935013-542a613a-9b83-45f6-8e6f-52b0d58bad4c.png)

#### delete 
![delete](https://user-images.githubusercontent.com/94010073/235935083-df8f6a31-10f8-4fe0-8154-3d85422f1211.png)

2023-05-04 01:33 UTC, duardoqueiroz requested changes
Resolva essas peia aí meu parceiro

2023-05-04 01:33 UTC, duardoqueiroz commented on app/Controllers/Http/UsersController.ts
> +    const data = request.only(['name', 'email', 'password', 'isAdmin'])
Use validators para poder validar os campos da requisição

2023-05-04 01:33 UTC, duardoqueiroz commented on app/Controllers/Http/UsersController.ts
> +    return users
retorne com uma resposta descente(utilizando status e passando os valores como parametros)

2023-05-04 01:33 UTC, duardoqueiroz commented on app/Controllers/Http/UsersController.ts
> +    return user
retorne com uma resposta descente(utilizando status e passando os valores como parametros)

2023-05-04 01:33 UTC, duardoqueiroz commented on app/Controllers/Http/UsersController.ts
> +    return user
retorne com uma resposta descente(utilizando status e passando os valores como parametros)

2023-05-04 01:33 UTC, duardoqueiroz commented on app/Controllers/Http/UsersController.ts
> +    const data = request.only(['name', 'email', 'password', 'isAdmin'])
utilize validators para validar esses campos

2023-05-07 05:54 UTC, adelsonsljunior commented
@duardoqueiroz, corrigi. Agora, agora vou de dormes

2023-05-08 17:17 UTC, duardoqueiroz requested changes
Quase lá, só quero que você faça mais uma coisa: utilize do conceito de policies nas rotas de destroy e update no UsersController para que apenas o próprio usuário atualize e delete seus dados. Para isso você vai precisar utilizar o [bouncer ](https://docs.adonisjs.com/guides/authorization) do adonis

2023-05-09 01:26 UTC, adelsonsljunior commented
@duardoqueiroz, bouncer e a policy de user implemendados. Vou ao dormes

2023-05-09 22:22 UTC, adelsonsljunior commented
@duardoqueiroz , 3 issues em 1 PR  😎

2023-05-19 22:36 UTC, duardoqueiroz approved these changes
Nice!

2023-05-23 14:22 UTC, adelsonsljunior commented
vou fazer o merge

2023-05-23 14:22 UTC, merged